### ISSUE TITLE
Dokumentálni, hogy mi elérhető az ONYA-ban és mi nem

### ISSUE THREAD

**Issue by Res42** [Res42/anyk-docker#10]
A Readme-be dokumentálni kéne, hogy honnan lehet tudni, hogy mi elérhető az ONYA-ban és mi nem.

**Elérhető:** <https://nav.gov.hu/nav/letoltesek/nyomtatvanykitolto_programok/nyomtatvanykitolto_programok_nav/bevallasok/21KATA.html>
![image](https://user-images.githubusercontent.com/2495806/137081509-c4195714-f842-4e8c-8f92-da034d06e4f4.png)
A piros szöveg.

**Nem elérhető:** <https://nav.gov.hu/nav/letoltesek/nyomtatvanykitolto_programok/nyomtatvanykitolto_programok_nav/bevallasok/21HIPA.html>
![image](https://user-images.githubusercontent.com/2495806/137081596-247d9e58-a0cc-4dea-a5a9-346a7ee48f6c.png)
A piros szöveg hiánya.

**Comment by zandraaperjesi** [comment]
Foglalnám az issuet.
