### ISSUE TITLE
Github Actions docker-compose átállás

### ISSUE THREAD

**Issue by Res42** [Res42/anyk-docker#12]
Át kéne állni erre: <https://docs.docker.com/compose/cli-command/#compose-v2-and-the-new-docker-compose-command> a Gitub Actions scriptekben.

Elvileg a runner VM-ben telepítve van az új verzió: <https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md>

**Comment by zandraaperjesi** [comment]
tudom hogy nagy a backlogom, de ez az issue is érdekelne :D
