### ISSUE TITLE
Retag or remove the previous docker images

### ISSUE THREAD

**Issue by Teko012** [Res42/anyk-docker#49]
@Res42 Can you retag the previous docker images from `latest` to `legacy` and `legacy-xyz` to avoid confusion? It might worth keeping it around in case there are some issues with the new ones, or if you have tried the new one and you think we can just remove it, that also works.

**Comment by Res42** [comment]
I tried out your new `base-ubuntu-xfce` image and it looks very good. I didn't try to submit a form, but everything else seems to be working well.

I retagged the old images as your requested. I don't know if there is a benefit to keeping them, but they can stay for now.
