### ISSUE TITLE
21HIPA image készítése

### ISSUE THREAD

**Issue by Res42** [Res42/anyk-docker#9]
Kijött a 21HIPA, amit a NAV szerint még mindig csak az ÁNYK-n keresztül lehet beadni.

<https://nav.gov.hu/nav/letoltesek/nyomtatvanykitolto_programok/nyomtatvanykitolto_programok_nav/bevallasok/21HIPA.html>

**Comment by zandraaperjesi** [comment]
Foglalnám

**Comment by Res42** [comment]
Mi a helyzet ezzel Zandraa? A budaörsiek és az egriek már epekedve várják ezt a feature-t.

**Comment by kerkoag** [comment]
@zandraaperjesi átveszem
